# Generated by Django 3.2.16 on 2022-12-20 17:58

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceCriteria',
            fields=[
                ('id', models.SmallIntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('date_from', core.fields.DateField(blank=True, db_column='StartDate', null=True)),
                ('date_to', core.fields.DateField(blank=True, db_column='EndDate', null=True)),
                ('health_facility', models.IntegerField(blank=True, db_column='HFID', null=True)),
                ('promptness', models.IntegerField(db_column='PromptnessInvoiceSubmission')),
                ('medecine_availability', models.IntegerField(blank=True, db_column='MedecineAvailability', null=True)),
                ('qualified_personnel', models.IntegerField(blank=True, db_column='QualifiedPersonel', null=True)),
                ('garbagecan_availability', models.IntegerField(blank=True, db_column='GarbagecanAvailable', null=True)),
                ('rooms_cleaness', models.IntegerField(blank=True, db_column='RoomCleaness', null=True)),
                ('waste_separation', models.IntegerField(blank=True, db_column='WasteSeparationSystem', null=True)),
                ('functionals_toilets', models.IntegerField(blank=True, db_column='FunctionalToilets', null=True)),
                ('sterilization_tools', models.IntegerField(blank=True, db_column='SterilizationTools', null=True)),
                ('is_validated', models.BooleanField(blank=True, db_column='isValidated', default=False, null=True)),
                ('record_date', models.DateTimeField(blank=True, db_column='RecordDate', null=True)),
            ],
            options={
                'db_table': 'tblPerformanceCriteria',
                'managed': True,
            },
        ),
    ]
