# Generated by Django 3.2.17 on 2023-05-11 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceCriteria',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('period', models.CharField(blank=True, db_column='Period', max_length=50, null=True)),
                ('health_facility', models.IntegerField(blank=True, db_column='HFID', null=True)),
                ('medecine_availability', models.IntegerField(blank=True, db_column='MedecineAvailability', null=True)),
                ('qualified_personnel', models.IntegerField(blank=True, db_column='QualifiedPersonel', null=True)),
                ('garbagecan_availability', models.IntegerField(blank=True, db_column='GarbagecanAvailable', null=True)),
                ('rooms_cleaness', models.IntegerField(blank=True, db_column='RoomCleaness', null=True)),
                ('waste_separation', models.IntegerField(blank=True, db_column='WasteSeparationSystem', null=True)),
                ('functionals_toilets', models.IntegerField(blank=True, db_column='FunctionalToilets', null=True)),
                ('sterilization_tools', models.IntegerField(blank=True, db_column='SterilizationTools', null=True)),
                ('is_validated', models.BooleanField(blank=True, db_column='isValidated', default=True, null=True)),
                ('record_date', models.DateTimeField(blank=True, db_column='RecordDate', null=True)),
                ('audit_user_id', models.IntegerField(blank=True, db_column='AuditUserId', null=True)),
                ('degre_of_rejection', models.IntegerField(blank=True, db_column='degreofRejection', default=0, null=True)),
                ('promptness_submission', models.IntegerField(blank=True, db_column='Promptness', default=0, null=True)),
                ('hf_score', models.IntegerField(blank=True, db_column='HFScore', default=0, null=True)),
            ],
            options={
                'db_table': 'tblPerformanceCriteria',
                'managed': True,
            },
        ),
    ]
