# Generated by Django 3.2.16 on 2023-01-18 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performancecriteria',
            name='date_from',
        ),
        migrations.RemoveField(
            model_name='performancecriteria',
            name='date_to',
        ),
        migrations.RemoveField(
            model_name='performancecriteria',
            name='promptness',
        ),
        migrations.AddField(
            model_name='performancecriteria',
            name='degre_of_rejection',
            field=models.DecimalField(blank=True, db_column='degreofRejection', decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='performancecriteria',
            name='hf_score',
            field=models.IntegerField(blank=True, db_column='HFScore', null=True),
        ),
        migrations.AddField(
            model_name='performancecriteria',
            name='period',
            field=models.CharField(blank=True, db_column='Period', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='performancecriteria',
            name='promptness_submission',
            field=models.DecimalField(blank=True, db_column='Promptness', decimal_places=2, max_digits=18, null=True),
        ),
    ]
